#!/usr/bin/env bun
/**
 * Custom codegen pass that runs after `openapi-ts`.
 *
 * `openapi-ts` produces the raw TypeScript types for every schema in the spec
 * (src/generated/openapi/). This script reads openapi.json directly and emits
 * the WebSocket-v2-shaped artifacts the library needs but that a generic
 * OpenAPI generator does not produce:
 *
 *   - actions.gen.ts       The tool/action command catalog (every v2 command,
 *                          its parameters, and whether it is a query or a
 *                          mutation) plus string-literal union types.
 *   - notifications.gen.ts The map from server push `msg_type` -> payload type,
 *                          built from the `Notification_<msg_type>` schemas the
 *                          server publishes in components.schemas.
 *
 * Both files are committed. Re-run `bun run generate` after syncing the spec.
 */

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const ROOT = join(import.meta.dir, '..');
const SPEC_PATH = join(ROOT, 'openapi.json');
const OUT_DIR = join(ROOT, 'src', 'generated');

interface OpenAPIProperty {
  type?: string;
  description?: string;
  enum?: string[];
  items?: { type?: string };
  'x-positional-index'?: number;
}

interface OpenAPIOperation {
  operationId?: string;
  summary?: string;
  description?: string;
  /** Authoritative: true when the command is queued for the next tick (two-phase). */
  'x-is-mutation'?: boolean;
  requestBody?: {
    content?: {
      'application/json'?: {
        schema?: {
          properties?: Record<string, OpenAPIProperty>;
          required?: string[];
        };
      };
    };
  };
}

interface OpenAPISpec {
  info: { version: string; 'x-gameserver-version'?: string };
  paths: Record<string, Record<string, OpenAPIOperation>>;
  components: { schemas: Record<string, unknown> };
}

interface ParamDef {
  name: string;
  type: string;
  required: boolean;
  description?: string;
  enumValues?: string[];
  positional?: number;
}

interface ActionDef {
  tool: string;
  action: string;
  /** Mutations are POSTs that queue for a tick; queries resolve synchronously. */
  kind: 'query' | 'mutation';
  summary?: string;
  params: ParamDef[];
}

const BANNER = `// AUTO-GENERATED by scripts/generate.ts from openapi.json. DO NOT EDIT.\n`;

function tsType(p: OpenAPIProperty): string {
  if (p.enum && p.enum.length) return p.enum.map((v) => JSON.stringify(v)).join(' | ');
  switch (p.type) {
    case 'integer':
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      return `${p.items?.type === 'integer' || p.items?.type === 'number' ? 'number' : 'string'}[]`;
    case 'object':
      return 'Record<string, unknown>';
    default:
      return 'string';
  }
}

function extractActions(spec: OpenAPISpec): ActionDef[] {
  const actions: ActionDef[] = [];
  for (const [path, methods] of Object.entries(spec.paths)) {
    const match = path.match(/^\/api\/v2\/([^/]+)\/([^/]+)$/);
    if (!match) continue;
    const [, tool, action] = match as unknown as [string, string, string];
    if (action === 'help') continue; // help is a GET meta-endpoint, not a game action
    const op = methods.post;
    if (!op) continue;

    const schema = op.requestBody?.content?.['application/json']?.schema;
    const required = new Set(schema?.required ?? []);
    const params: ParamDef[] = Object.entries(schema?.properties ?? {}).map(([name, prop]) => ({
      name,
      type: tsType(prop),
      required: required.has(name),
      description: prop.description,
      enumValues: prop.enum,
      positional: prop['x-positional-index'],
    }));

    // `x-is-mutation` is authoritative: true => queued for next tick (two-phase
    // result + action_result). Absent/false => synchronous result.
    const kind: ActionDef['kind'] = op['x-is-mutation'] ? 'mutation' : 'query';
    actions.push({ tool, action, kind, summary: op.summary, params });
  }
  actions.sort((a, b) => (a.tool + a.action).localeCompare(b.tool + b.action));
  return actions;
}

function emitActions(spec: OpenAPISpec, actions: ActionDef[]): string {
  const tools = [...new Set(actions.map((a) => a.tool))].sort();
  const actionNames = [...new Set(actions.map((a) => a.action))].sort();

  let out = BANNER;
  out += `// Source spec: ${spec.info['x-gameserver-version'] ?? spec.info.version}\n\n`;

  out += `export type ToolName =\n  | ${tools.map((t) => JSON.stringify(t)).join('\n  | ')};\n\n`;
  out += `export type ActionName =\n  | ${actionNames.map((a) => JSON.stringify(a)).join('\n  | ')};\n\n`;

  out += `export interface ActionParam {\n`;
  out += `  readonly name: string;\n  readonly type: string;\n  readonly required: boolean;\n`;
  out += `  readonly description?: string;\n  readonly enumValues?: readonly string[];\n  readonly positional?: number;\n}\n\n`;

  out += `export interface ActionDef {\n`;
  out += `  readonly tool: ToolName;\n  readonly action: ActionName;\n  readonly kind: 'query' | 'mutation';\n`;
  out += `  readonly summary?: string;\n  readonly params: readonly ActionParam[];\n}\n\n`;

  out += `/** Every v2 command, keyed by "tool/action". */\n`;
  out += `export const ACTIONS: Record<string, ActionDef> = {\n`;
  for (const a of actions) {
    const key = `${a.tool}/${a.action}`;
    const params = a.params
      .map((p) => {
        const bits = [`name: ${JSON.stringify(p.name)}`, `type: ${JSON.stringify(p.type)}`, `required: ${p.required}`];
        if (p.description) bits.push(`description: ${JSON.stringify(p.description)}`);
        if (p.enumValues) bits.push(`enumValues: ${JSON.stringify(p.enumValues)}`);
        if (p.positional !== undefined) bits.push(`positional: ${p.positional}`);
        return `      { ${bits.join(', ')} }`;
      })
      .join(',\n');
    out += `  ${JSON.stringify(key)}: {\n`;
    out += `    tool: ${JSON.stringify(a.tool)}, action: ${JSON.stringify(a.action)}, kind: ${JSON.stringify(a.kind)},\n`;
    if (a.summary) out += `    summary: ${JSON.stringify(a.summary)},\n`;
    out += `    params: [${params ? `\n${params},\n    ` : ''}],\n`;
    out += `  },\n`;
  }
  out += `};\n`;
  return out;
}

/** Mirror openapi-ts's schema-name -> TS identifier transform (PascalCase). */
function tsIdentifier(schemaName: string): string {
  return schemaName
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

function emitNotifications(spec: OpenAPISpec): string {
  const schemaNames = Object.keys(spec.components.schemas);
  const typed = schemaNames
    .filter((n) => n.startsWith('Notification_'))
    .map((n) => ({ msgType: n.slice('Notification_'.length), schema: tsIdentifier(n) }))
    .sort((a, b) => a.msgType.localeCompare(b.msgType));

  let out = BANNER;
  out += `// Server push frames carry a \`type\` (msg_type) and a \`payload\`. The server\n`;
  out += `// publishes a typed schema for some of them as \`Notification_<msg_type>\`;\n`;
  out += `// those are imported below. Push frames without a published schema fall back\n`;
  out += `// to \`Record<string, unknown>\` until the server types them (incremental work).\n\n`;

  out += `import type {\n${typed.map((t) => `  ${t.schema},`).join('\n')}\n} from './openapi/types.gen.ts';\n\n`;

  out += `/** msg_type values that have a published payload schema. */\n`;
  out += `export type TypedNotificationType =\n  | ${typed.map((t) => JSON.stringify(t.msgType)).join('\n  | ')};\n\n`;

  out += `/** Maps a typed push msg_type to its payload type. */\n`;
  out += `export interface NotificationPayloads {\n`;
  for (const t of typed) out += `  ${JSON.stringify(t.msgType)}: ${t.schema};\n`;
  out += `}\n\n`;

  out += `/** Names of every push msg_type with a published schema, for runtime checks. */\n`;
  out += `export const TYPED_NOTIFICATION_TYPES = [\n${typed.map((t) => `  ${JSON.stringify(t.msgType)},`).join('\n')}\n] as const;\n`;
  return out;
}

/** Method/param identifier base for a tool/action, e.g. spacemolt_market/view_market -> SpacemoltMarketViewMarket. */
function commandTypeName(tool: string, action: string): string {
  return tsIdentifier(`${tool}_${action}`);
}

/**
 * Emit the ergonomic command facade: a typed param interface per parameterized
 * action, a `Commands` interface grouping every action under its tool (with the
 * right query/mutation return type), and a `buildCommands(dispatch)` runtime.
 */
function emitCommands(actions: ActionDef[]): string {
  const byTool = new Map<string, ActionDef[]>();
  for (const a of actions) {
    const list = byTool.get(a.tool) ?? [];
    list.push(a);
    byTool.set(a.tool, list);
  }
  const tools = [...byTool.keys()].sort();

  let out = BANNER;
  out += `import type { MutationResult, QueryResult } from '../protocol.ts';\n\n`;

  // Param interfaces (only for actions that take parameters).
  for (const a of actions) {
    if (!a.params.length) continue;
    out += `export interface ${commandTypeName(a.tool, a.action)}Params {\n`;
    for (const p of a.params) {
      if (p.description) out += `  /** ${p.description.replace(/\*\//g, '*\\/')} */\n`;
      out += `  ${p.name}${p.required ? '' : '?'}: ${p.type};\n`;
    }
    out += `}\n\n`;
  }

  const ret = (a: ActionDef): string => (a.kind === 'mutation' ? 'MutationResult' : 'QueryResult');
  const signature = (a: ActionDef): string => {
    if (!a.params.length) return `(): Promise<${ret(a)}>`;
    const paramsType = `${commandTypeName(a.tool, a.action)}Params`;
    const optional = a.params.every((p) => !p.required);
    return `(params${optional ? '?' : ''}: ${paramsType}): Promise<${ret(a)}>`;
  };

  // Commands interface, grouped by tool.
  out += `export interface Commands {\n`;
  for (const tool of tools) {
    out += `  ${tool}: {\n`;
    for (const a of byTool.get(tool)!) {
      if (a.summary) out += `    /** ${a.summary.replace(/\*\//g, '*\\/')} */\n`;
      out += `    ${a.action}${signature(a)};\n`;
    }
    out += `  };\n`;
  }
  out += `}\n\n`;

  out += `export type CommandDispatch = (\n`;
  out += `  tool: string,\n  action: string,\n  payload?: Record<string, unknown>,\n`;
  out += `) => Promise<QueryResult | MutationResult>;\n\n`;

  // Runtime: bind each tool/action to the dispatcher. Types come from Commands.
  out += `export function buildCommands(dispatch: CommandDispatch): Commands {\n`;
  out += `  const bind = (tool: string, action: string) => (params?: Record<string, unknown>) => dispatch(tool, action, params);\n`;
  out += `  return {\n`;
  for (const tool of tools) {
    out += `    ${tool}: {\n`;
    for (const a of byTool.get(tool)!) {
      out += `      ${a.action}: bind(${JSON.stringify(tool)}, ${JSON.stringify(a.action)}),\n`;
    }
    out += `    },\n`;
  }
  out += `  } as unknown as Commands;\n`;
  out += `}\n`;
  return out;
}

function main() {
  const spec: OpenAPISpec = JSON.parse(readFileSync(SPEC_PATH, 'utf-8'));
  const actions = extractActions(spec);

  writeFileSync(join(OUT_DIR, 'actions.gen.ts'), emitActions(spec, actions));
  writeFileSync(join(OUT_DIR, 'notifications.gen.ts'), emitNotifications(spec));
  writeFileSync(join(OUT_DIR, 'commands.gen.ts'), emitCommands(actions));

  const queries = actions.filter((a) => a.kind === 'query').length;
  const mutations = actions.length - queries;
  const typedNotifs = Object.keys(spec.components.schemas).filter((n) => n.startsWith('Notification_')).length;
  console.log(
    `generate.ts: ${actions.length} actions (${queries} query / ${mutations} mutation), ` +
      `${typedNotifs} typed notifications, spec ${spec.info['x-gameserver-version'] ?? spec.info.version}`,
  );
}

main();
