#!/usr/bin/env bun
/**
 * Custom codegen pass that runs after `openapi-ts`.
 *
 * `openapi-ts` produces the raw TypeScript types for every schema in the spec
 * (src/generated/openapi/). This script reads openapi.json directly and emits
 * the WebSocket-v2-shaped artifacts the library needs but that a generic
 * OpenAPI generator does not produce:
 *
 *   - actions.gen.ts       The tool/action command catalog (every v2 command,
 *                          its parameters, and whether it is a query or a
 *                          mutation) plus string-literal union types.
 *   - notifications.gen.ts The map from server push `msg_type` -> payload type,
 *                          built from the `Notification_<msg_type>` schemas the
 *                          server publishes in components.schemas.
 *   - commands.gen.ts      The ergonomic typed command facade (see emitCommands).
 *   - COMMANDS.md (root)   A flat, greppable markdown reference of every command
 *                          and its typed signature — the discovery surface for
 *                          coding agents that don't drive a live LSP.
 *
 * All files are committed. Re-run `bun run generate` after syncing the spec.
 */

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const ROOT = join(import.meta.dir, '..');
const SPEC_PATH = join(ROOT, 'openapi.json');
const OUT_DIR = join(ROOT, 'src', 'generated');
const COMMANDS_DOC_PATH = join(ROOT, 'COMMANDS.md');

interface OpenAPIProperty {
  type?: string;
  description?: string;
  enum?: string[];
  items?: OpenAPIProperty;
  properties?: Record<string, OpenAPIProperty>;
  required?: string[];
  'x-positional-index'?: number;
}

interface OpenAPISchemaRef {
  $ref?: string;
  allOf?: OpenAPISchemaRef[];
  properties?: Record<string, OpenAPISchemaRef>;
}

interface OpenAPIOperation {
  operationId?: string;
  summary?: string;
  description?: string;
  /** Authoritative: true when the command is queued for the next tick (two-phase). */
  'x-is-mutation'?: boolean;
  requestBody?: {
    content?: {
      'application/json'?: {
        schema?: {
          properties?: Record<string, OpenAPIProperty>;
          required?: string[];
        };
      };
    };
  };
  responses?: Record<
    string,
    { content?: { 'application/json'?: { schema?: OpenAPISchemaRef } } }
  >;
}

interface OpenAPISpec {
  info: { version: string; 'x-gameserver-version'?: string };
  paths: Record<string, Record<string, OpenAPIOperation>>;
  components: { schemas: Record<string, unknown> };
}

export interface ParamDef {
  name: string;
  type: string;
  required: boolean;
  description?: string;
  enumValues?: string[];
  positional?: number;
}

export interface ActionDef {
  tool: string;
  action: string;
  /** Mutations are POSTs that queue for a tick; queries resolve synchronously. */
  kind: 'query' | 'mutation';
  summary?: string;
  params: ParamDef[];
  /** TS type name of the query's `structuredContent` response, when the spec declares one. */
  responseType?: string;
  /** TS type name of the mutation's `delta.details` response, when the spec declares one. */
  detailsType?: string;
}

const BANNER = `// AUTO-GENERATED by scripts/generate.ts from openapi.json. DO NOT EDIT.\n`;

function tsType(p: OpenAPIProperty): string {
  if (p.enum && p.enum.length) return p.enum.map((v) => JSON.stringify(v)).join(' | ');
  switch (p.type) {
    case 'integer':
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array': {
      if (!p.items) return 'string[]';
      const el = tsType(p.items);
      // An enum element is a bare union (`"a" | "b"`); `[]` binds tighter than
      // `|`, so it must be parenthesized or it parses as `"a" | ("b"[])`.
      return p.items.enum?.length ? `(${el})[]` : `${el}[]`;
    }
    case 'object':
      if (p.properties && Object.keys(p.properties).length) {
        const req = new Set(p.required ?? []);
        const fields = Object.entries(p.properties).map(
          ([name, prop]) => `${name}${req.has(name) ? '' : '?'}: ${tsType(prop)}`,
        );
        return `{ ${fields.join('; ')} }`;
      }
      return 'Record<string, unknown>';
    default:
      return 'string';
  }
}

/**
 * Map a spec schema name to the exact type identifier openapi-ts exported for it,
 * by matching against the real exports in types.gen.ts (normalized, case- and
 * separator-insensitive). openapi-ts re-cases acronyms (`GetPOIResponse` ->
 * `GetPoiResponse`), so we resolve against the source of truth rather than guess.
 */
let exportedTypeIndex: Map<string, string> | null = null;
function exportedTypeNames(): Map<string, string> {
  if (exportedTypeIndex) return exportedTypeIndex;
  const index = new Map<string, string>();
  const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');
  try {
    const src = readFileSync(join(OUT_DIR, 'openapi', 'types.gen.ts'), 'utf-8');
    for (const m of src.matchAll(/^export type (\w+)\b/gm)) index.set(norm(m[1]!), m[1]!);
  } catch {
    // types.gen.ts not generated yet (openapi-ts runs first in `bun run generate`).
  }
  exportedTypeIndex = index;
  return index;
}

/**
 * Pull the `structuredContent` response type from a 200 response. The response
 * schema is `allOf: [V2Response, { properties: { structuredContent: { $ref } } }]`;
 * we resolve that `$ref`'s basename to the matching exported type name.
 *
 * Only resolves a *plain* `$ref` on `structuredContent` itself — this is what
 * every query action's response looks like (verified against the live spec:
 * every non-mutation action resolves this way). A mutation's
 * `structuredContent` is shaped differently (the full state delta, not a
 * single ref) — see `extractMutationDetailsType` for that case.
 */
function extractResponseType(op: OpenAPIOperation): string | undefined {
  const schema = op.responses?.['200']?.content?.['application/json']?.schema;
  if (!schema) return undefined;
  const parts = schema.allOf ?? [schema];
  const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');
  for (const part of parts) {
    const ref = part.properties?.structuredContent?.$ref;
    if (ref) return exportedTypeNames().get(norm(ref.split('/').pop()!));
  }
  return undefined;
}

/**
 * Pull the per-action `details` response type from a mutation's 200 response.
 * A mutation's `structuredContent` is the full state delta (`V2GameState`)
 * plus an action-specific `details` field:
 * `allOf: [V2GameState, { properties: { details: { $ref } } } ]`. Resolves
 * that `$ref`'s basename to the matching exported type name, same as
 * `extractResponseType` does for queries. Verified against the live spec:
 * every one of the 141 mutation actions has this exact shape, no exceptions —
 * so an undefined return here means the schema changed, not that this is an
 * expected gap.
 */
function extractMutationDetailsType(op: OpenAPIOperation): string | undefined {
  const schema = op.responses?.['200']?.content?.['application/json']?.schema;
  if (!schema) return undefined;
  const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');
  for (const part of schema.allOf ?? [schema]) {
    const sc = part.properties?.structuredContent;
    if (!sc) continue;
    for (const scPart of sc.allOf ?? [sc]) {
      const ref = scPart.properties?.details?.$ref;
      if (ref) return exportedTypeNames().get(norm(ref.split('/').pop()!));
    }
  }
  return undefined;
}

export function extractActions(spec: OpenAPISpec): ActionDef[] {
  const actions: ActionDef[] = [];
  for (const [path, methods] of Object.entries(spec.paths)) {
    const match = path.match(/^\/api\/v2\/([^/]+)\/([^/]+)$/);
    if (!match) continue;
    const [, tool, action] = match as unknown as [string, string, string];
    if (action === 'help') continue; // help is a GET meta-endpoint, not a game action
    const op = methods.post;
    if (!op) continue;

    const schema = op.requestBody?.content?.['application/json']?.schema;
    const required = new Set(schema?.required ?? []);
    const params: ParamDef[] = Object.entries(schema?.properties ?? {}).map(([name, prop]) => ({
      name,
      type: tsType(prop),
      required: required.has(name),
      description: prop.description,
      enumValues: prop.enum,
      positional: prop['x-positional-index'],
    }));

    // `x-is-mutation` is authoritative: true => queued for next tick (two-phase
    // result + action_result). Absent/false => synchronous result.
    const kind: ActionDef['kind'] = op['x-is-mutation'] ? 'mutation' : 'query';
    // Queries resolve with a typed `structuredContent`; pull its schema name from
    // the 200 response so the facade can return QueryResult<ResponseType>.
    const responseType = kind === 'query' ? extractResponseType(op) : undefined;
    // Mutations resolve with a typed `delta.details`; pull its schema name so
    // the facade can return MutationResult<DetailsType> instead of leaving
    // `details` — the one part of the delta that's actually action-specific —
    // untyped.
    const detailsType = kind === 'mutation' ? extractMutationDetailsType(op) : undefined;
    actions.push({ tool, action, kind, summary: op.summary, params, responseType, detailsType });
  }
  actions.sort((a, b) => (a.tool + a.action).localeCompare(b.tool + b.action));
  return actions;
}

function emitActions(spec: OpenAPISpec, actions: ActionDef[]): string {
  const tools = [...new Set(actions.map((a) => a.tool))].sort();
  const actionNames = [...new Set(actions.map((a) => a.action))].sort();

  let out = BANNER;
  out += `// Source spec: ${spec.info['x-gameserver-version'] ?? spec.info.version}\n\n`;

  out += `/** The gameserver spec version this command surface was generated from. */\n`;
  out += `export const GENERATED_SPEC_VERSION = ${JSON.stringify(spec.info['x-gameserver-version'] ?? spec.info.version)};\n\n`;

  out += `export type ToolName =\n  | ${tools.map((t) => JSON.stringify(t)).join('\n  | ')};\n\n`;
  out += `export type ActionName =\n  | ${actionNames.map((a) => JSON.stringify(a)).join('\n  | ')};\n\n`;

  out += `export interface ActionParam {\n`;
  out += `  readonly name: string;\n  readonly type: string;\n  readonly required: boolean;\n`;
  out += `  readonly description?: string;\n  readonly enumValues?: readonly string[];\n  readonly positional?: number;\n}\n\n`;

  out += `export interface ActionDef {\n`;
  out += `  readonly tool: ToolName;\n  readonly action: ActionName;\n  readonly kind: 'query' | 'mutation';\n`;
  out += `  readonly summary?: string;\n  readonly params: readonly ActionParam[];\n`;
  out += `  /** TS type name of the query's structuredContent response (queries with a published response schema). */\n`;
  out += `  readonly responseType?: string;\n`;
  out += `  /** TS type name of the mutation's delta.details response (mutations with a published details schema). */\n`;
  out += `  readonly detailsType?: string;\n}\n\n`;

  out += `/** Every v2 command, keyed by "tool/action". */\n`;
  out += `export const ACTIONS: Record<string, ActionDef> = {\n`;
  for (const a of actions) {
    const key = `${a.tool}/${a.action}`;
    const params = a.params
      .map((p) => {
        const bits = [`name: ${JSON.stringify(p.name)}`, `type: ${JSON.stringify(p.type)}`, `required: ${p.required}`];
        if (p.description) bits.push(`description: ${JSON.stringify(p.description)}`);
        if (p.enumValues) bits.push(`enumValues: ${JSON.stringify(p.enumValues)}`);
        if (p.positional !== undefined) bits.push(`positional: ${p.positional}`);
        return `      { ${bits.join(', ')} }`;
      })
      .join(',\n');
    out += `  ${JSON.stringify(key)}: {\n`;
    out += `    tool: ${JSON.stringify(a.tool)}, action: ${JSON.stringify(a.action)}, kind: ${JSON.stringify(a.kind)},\n`;
    if (a.summary) out += `    summary: ${JSON.stringify(a.summary)},\n`;
    if (a.responseType) out += `    responseType: ${JSON.stringify(a.responseType)},\n`;
    if (a.detailsType) out += `    detailsType: ${JSON.stringify(a.detailsType)},\n`;
    out += `    params: [${params ? `\n${params},\n    ` : ''}],\n`;
    out += `  },\n`;
  }
  out += `};\n`;
  return out;
}

/** Mirror openapi-ts's schema-name -> TS identifier transform (PascalCase). */
function tsIdentifier(schemaName: string): string {
  return schemaName
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

function emitNotifications(spec: OpenAPISpec): string {
  const schemaNames = Object.keys(spec.components.schemas);
  const typed = schemaNames
    .filter((n) => n.startsWith('Notification_'))
    .map((n) => ({ msgType: n.slice('Notification_'.length), schema: tsIdentifier(n) }))
    .sort((a, b) => a.msgType.localeCompare(b.msgType));

  let out = BANNER;
  out += `// Server push frames carry a \`type\` (msg_type) and a \`payload\`. The server\n`;
  out += `// publishes a typed schema for some of them as \`Notification_<msg_type>\`;\n`;
  out += `// those are imported below. Push frames without a published schema fall back\n`;
  out += `// to \`Record<string, unknown>\` until the server types them (incremental work).\n\n`;

  out += `import type {\n${typed.map((t) => `  ${t.schema},`).join('\n')}\n} from './openapi/types.gen.ts';\n\n`;

  out += `/** msg_type values that have a published payload schema. */\n`;
  out += `export type TypedNotificationType =\n  | ${typed.map((t) => JSON.stringify(t.msgType)).join('\n  | ')};\n\n`;

  out += `/** Maps a typed push msg_type to its payload type. */\n`;
  out += `export interface NotificationPayloads {\n`;
  for (const t of typed) out += `  ${JSON.stringify(t.msgType)}: ${t.schema};\n`;
  out += `}\n\n`;

  out += `/** Names of every push msg_type with a published schema, for runtime checks. */\n`;
  out += `export const TYPED_NOTIFICATION_TYPES = [\n${typed.map((t) => `  ${JSON.stringify(t.msgType)},`).join('\n')}\n] as const;\n`;
  return out;
}

/** Method/param identifier base for a tool/action, e.g. spacemolt_market/view_market -> SpacemoltMarketViewMarket. */
function commandTypeName(tool: string, action: string): string {
  return tsIdentifier(`${tool}_${action}`);
}

/**
 * Emit the ergonomic command facade: a typed param interface per parameterized
 * action, a `Commands` interface grouping every action under its tool (with the
 * right query/mutation return type), and a `buildCommands(dispatch)` runtime.
 */
function emitCommands(actions: ActionDef[]): string {
  const byTool = new Map<string, ActionDef[]>();
  for (const a of actions) {
    const list = byTool.get(a.tool) ?? [];
    list.push(a);
    byTool.set(a.tool, list);
  }
  const tools = [...byTool.keys()].sort();

  let out = BANNER;
  out += `import type { MutationResult, QueryResult } from '../protocol.ts';\n`;
  // Import the generated response types so query commands return them directly,
  // and mutation commands return their delta.details typed too (not just the
  // generic StateDelta shape every mutation would otherwise share).
  const responseTypes = [
    ...new Set(
      actions
        .map((a) => (a.kind === 'query' ? a.responseType : a.detailsType))
        .filter((t): t is string => !!t),
    ),
  ].sort();
  if (responseTypes.length) {
    out += `import type {\n${responseTypes.map((t) => `  ${t},`).join('\n')}\n} from './openapi/types.gen.ts';\n`;
  }
  out += `\n`;

  // Param interfaces (only for actions that take parameters).
  for (const a of actions) {
    if (!a.params.length) continue;
    out += `export interface ${commandTypeName(a.tool, a.action)}Params {\n`;
    for (const p of a.params) {
      if (p.description) out += `  /** ${p.description.replace(/\*\//g, '*\\/')} */\n`;
      out += `  ${p.name}${p.required ? '' : '?'}: ${p.type};\n`;
    }
    out += `}\n\n`;
  }

  const ret = (a: ActionDef): string => {
    if (a.kind === 'mutation') return a.detailsType ? `MutationResult<${a.detailsType}>` : 'MutationResult';
    return a.responseType ? `QueryResult<${a.responseType}>` : 'QueryResult';
  };
  const signature = (a: ActionDef): string => {
    if (!a.params.length) return `(): Promise<${ret(a)}>`;
    const paramsType = `${commandTypeName(a.tool, a.action)}Params`;
    const optional = a.params.every((p) => !p.required);
    return `(params${optional ? '?' : ''}: ${paramsType}): Promise<${ret(a)}>`;
  };

  // Commands interface, grouped by tool.
  out += `export interface Commands {\n`;
  for (const tool of tools) {
    out += `  ${tool}: {\n`;
    for (const a of byTool.get(tool)!) {
      if (a.summary) out += `    /** ${a.summary.replace(/\*\//g, '*\\/')} */\n`;
      out += `    ${a.action}${signature(a)};\n`;
    }
    out += `  };\n`;
  }
  out += `}\n\n`;

  out += `export type CommandDispatch = (\n`;
  out += `  tool: string,\n  action: string,\n  payload?: Record<string, unknown>,\n`;
  out += `) => Promise<QueryResult | MutationResult>;\n\n`;

  // Runtime: bind each tool/action to the dispatcher. Types come from Commands.
  out += `export function buildCommands(dispatch: CommandDispatch): Commands {\n`;
  out += `  const bind = (tool: string, action: string) => (params?: Record<string, unknown>) => dispatch(tool, action, params);\n`;
  out += `  return {\n`;
  for (const tool of tools) {
    out += `    ${tool}: {\n`;
    for (const a of byTool.get(tool)!) {
      out += `      ${a.action}: bind(${JSON.stringify(tool)}, ${JSON.stringify(a.action)}),\n`;
    }
    out += `    },\n`;
  }
  out += `  } as unknown as Commands;\n`;
  out += `}\n`;
  return out;
}

/** Render an action's params as a TypeScript object-type literal, e.g. `{ id: string; quantity?: number }`. */
function renderParamLiteral(action: ActionDef): string {
  if (!action.params.length) return '()';
  const inner = action.params.map((p) => `${p.name}${p.required ? '' : '?'}: ${p.type}`).join('; ');
  return `({ ${inner} })`;
}

/**
 * Emit COMMANDS.md — a flat, greppable reference of every command and its typed
 * signature. This is the discovery surface for coding agents: a human in an IDE
 * sees these signatures via type hints, but an agent typically does not, so it
 * guesses. One file it can read (or grep) lists the whole command surface.
 */
export function emitCommandsDoc(spec: OpenAPISpec, actions: ActionDef[]): string {
  const byTool = new Map<string, ActionDef[]>();
  for (const a of actions) {
    const list = byTool.get(a.tool) ?? [];
    list.push(a);
    byTool.set(a.tool, list);
  }
  const tools = [...byTool.keys()].sort();
  const version = spec.info['x-gameserver-version'] ?? spec.info.version;

  let out = `<!-- AUTO-GENERATED by scripts/generate.ts from openapi.json. DO NOT EDIT. -->\n`;
  out += `# SpaceMolt command reference\n\n`;
  out += `Every command in \`@spacemolt/lib\`, generated from the live server spec (\`${version}\`). `;
  out += `**${actions.length} commands across ${tools.length} tools.**\n\n`;
  out += `## How to call a command\n\n`;
  out += `Every command is a typed method on a connected \`Account\`, grouped by tool:\n\n`;
  out += '```ts\n';
  out += `await account.commands.<tool>.<action>(params);\n`;
  out += `await account.commands.spacemolt.jump({ id: 'sol' });          // mutation\n`;
  out += `const status = await account.commands.spacemolt.get_status();  // query\n`;
  out += '```\n\n';
  out += `- **query** — resolves immediately. \`structuredContent\` is typed to the response shown after \`→\` (the command facade returns \`QueryResult<ResponseType>\`, so no cast). Grep \`src/generated/openapi/types.gen.ts\` for the shape.\n`;
  out += `- **mutation** — queued for the next game tick. \`await\` resolves when the action actually executes (which can be several ticks later for \`travel\`/\`jump\`), and the local state cache is already updated by then. Mutations are serialized one-in-flight per account. \`delta.details\` is typed to the response shown after \`→\` (the facade returns \`MutationResult<DetailsType>\`) — the rest of \`delta\` is the generic state-delta shape shared by every mutation.\n\n`;
  out += `> **Agents: typecheck before you run.** Every command name and parameter below is statically typed. Run \`bun run typecheck\` (or \`npx tsc --noEmit\`) before executing a script — a hallucinated command or wrong field is a compile error here, not a confusing runtime failure. This is the fastest way to confirm a call is valid without an IDE.\n\n`;

  out += `## Tools\n\n`;
  for (const tool of tools) {
    out += `- [\`${tool}\`](#${tool}) — ${byTool.get(tool)!.length} commands\n`;
  }
  out += `\n`;

  for (const tool of tools) {
    out += `## ${tool}\n\n`;
    out += `Call as \`account.commands.${tool}.<action>(...)\`.\n\n`;
    for (const a of byTool.get(tool)!) {
      const summary = a.summary ? ` — ${a.summary}` : '';
      const returns = a.responseType
        ? ` → \`${a.responseType}\``
        : a.detailsType
          ? ` → delta.details: \`${a.detailsType}\``
          : '';
      out += `- \`${a.action}${renderParamLiteral(a)}\` · *${a.kind}*${returns}${summary}\n`;
    }
    out += `\n`;
  }
  return out;
}

function main() {
  const spec: OpenAPISpec = JSON.parse(readFileSync(SPEC_PATH, 'utf-8'));
  const actions = extractActions(spec);

  writeFileSync(join(OUT_DIR, 'actions.gen.ts'), emitActions(spec, actions));
  writeFileSync(join(OUT_DIR, 'notifications.gen.ts'), emitNotifications(spec));
  writeFileSync(join(OUT_DIR, 'commands.gen.ts'), emitCommands(actions));
  writeFileSync(COMMANDS_DOC_PATH, emitCommandsDoc(spec, actions));

  const queries = actions.filter((a) => a.kind === 'query').length;
  const mutations = actions.length - queries;
  const typedNotifs = Object.keys(spec.components.schemas).filter((n) => n.startsWith('Notification_')).length;
  console.log(
    `generate.ts: ${actions.length} actions (${queries} query / ${mutations} mutation), ` +
      `${typedNotifs} typed notifications, spec ${spec.info['x-gameserver-version'] ?? spec.info.version}`,
  );
}

if (import.meta.main) main();
