#!/usr/bin/env bun
/**
 * Generates the repo-root `RECIPES.md` — a flat, greppable reference of every
 * recipe and item in the catalog (`GET /api/catalog.json`), mirroring the role
 * `COMMANDS.md` plays for commands (see scripts/generate.ts). Unlike
 * COMMANDS.md this is not wired into `bun run generate` / CI sync, since the
 * catalog is fetched over HTTP (rate limited) rather than read from the
 * committed openapi.json — run it by hand after a catalog change:
 *
 *   bun run generate:recipes
 *   bun run scripts/generate-recipes.ts --from path/to/catalog.json
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Catalog, CatalogItem, CatalogRecipe } from '../src/data/catalog.ts';
import { fetchCatalog } from '../src/data/catalog.ts';

const ROOT = join(import.meta.dir, '..');
const OUT_PATH = join(ROOT, 'RECIPES.md');

function titleCase(s: string): string {
  return s.replace(/\w\S*/g, (w) => w.charAt(0).toUpperCase() + w.slice(1));
}

function recipeFlags(r: CatalogRecipe): string {
  const flags: string[] = [];
  if (r.facility_only) flags.push('[facility-only]');
  if (r.hidden) flags.push('[hidden]');
  if (r.category === 'Ship Passive') flags.push('[ship-passive]');
  if (r.package_operation) flags.push(`[package:${r.package_operation}]`);
  if (r.no_recycle) flags.push('[no-recycle]');
  return flags.length ? ` ${flags.join(' ')}` : '';
}

function formatQty(item_id: string, quantity: number): string {
  return `\`${quantity} ${item_id}\``;
}

/** Regular items carry `category`; modules carry `type`/`slot` instead. */
function itemCategory(item: CatalogItem): string {
  return (item as { category?: string }).category ?? (item as { type?: string }).type ?? 'unknown';
}

function itemSource(item: CatalogItem, madeByCount: number): string {
  switch ((item as { extracted_by?: string }).extracted_by) {
    case 'mining':
      return 'mined';
    case 'gas':
      return 'gas';
    case 'ice':
      return 'ice';
    case 'rad':
      return 'rad';
    default:
      return madeByCount > 0 ? 'crafted' : 'unknown';
  }
}

export function generateRecipesDoc(catalog: Catalog): string {
  const recipes = [...catalog.recipes].sort((a, b) => a.id.localeCompare(b.id));
  const byCategory = new Map<string, CatalogRecipe[]>();
  for (const r of recipes) {
    const list = byCategory.get(r.category) ?? [];
    list.push(r);
    byCategory.set(r.category, list);
  }
  const categories = [...byCategory.keys()].sort((a, b) => a.localeCompare(b));

  const madeBy = new Map<string, number>();
  const usedBy = new Map<string, number>();
  const itemIds = new Set<string>();
  for (const r of recipes) {
    for (const inp of r.inputs) {
      itemIds.add(inp.item_id);
      usedBy.set(inp.item_id, (usedBy.get(inp.item_id) ?? 0) + 1);
    }
    for (const out of r.outputs) {
      itemIds.add(out.item_id);
      madeBy.set(out.item_id, (madeBy.get(out.item_id) ?? 0) + 1);
    }
  }
  const itemsById = new Map(catalog.items.map((i) => [i.id, i] as const));

  const lines: string[] = [];
  lines.push('<!-- AUTO-GENERATED by scripts/generate-recipes.ts from the catalog. DO NOT EDIT. -->');
  lines.push('# SpaceMolt recipe reference');
  lines.push('');
  lines.push(
    `Every recipe and every item that appears in a recipe, generated from the live catalog (\`${catalog.version}\`).`,
  );
  lines.push('');
  lines.push('## Grep conventions');
  lines.push('');
  lines.push(
    '- Each recipe line starts with `- \\`recipe_id\\`` — grep an id or `inputs:`/`outputs:` to trace a chain.',
  );
  lines.push("- Find what makes an item: `rg '→ outputs:.*item_id' RECIPES.md` or just `rg 'item_id' RECIPES.md`.");
  lines.push(
    '- Flags appended after the time: `[facility-only]`, `[hidden]`, `[ship-passive]`, `[package:pack]`/`[package:unpack]`, `[no-recycle]`.',
  );
  lines.push(
    '- The final `## Items` section lists every item referenced by a recipe, with counts of recipes that make/use it.',
  );
  lines.push('');

  for (const cat of categories) {
    lines.push(`## ${titleCase(cat)}`);
    lines.push('');
    const catRecipes = byCategory.get(cat) ?? [];
    for (const r of catRecipes) {
      const inputs = r.inputs.map((i) => formatQty(i.item_id, i.quantity)).join(' + ');
      const outputs = r.outputs.map((o) => formatQty(o.item_id, o.quantity)).join(' + ');
      lines.push(
        `- \`${r.id}\` — ${r.name} · inputs: ${inputs} → outputs: ${outputs} · ${r.crafting_time}s${recipeFlags(r)}`,
      );
    }
    lines.push('');
  }

  lines.push('## Items');
  lines.push('');
  for (const id of [...itemIds].sort((a, b) => a.localeCompare(b))) {
    const item = itemsById.get(id);
    const name = item?.name ?? id;
    const category = item ? itemCategory(item) : 'unknown';
    const made = madeBy.get(id) ?? 0;
    const used = usedBy.get(id) ?? 0;
    const source = item ? itemSource(item, made) : made > 0 ? 'crafted' : 'unknown';
    lines.push(
      `- \`${id}\` — ${name} · ${category} · source: ${source} · made by: ${made} recipes · used by: ${used} recipes`,
    );
  }
  lines.push('');

  return lines.join('\n');
}

async function main() {
  const fromIdx = process.argv.indexOf('--from');
  let catalog: Catalog;
  if (fromIdx !== -1) {
    const path = process.argv[fromIdx + 1];
    if (!path) throw new Error('--from requires a path');
    const data = JSON.parse(await Bun.file(path).text());
    catalog = data as Catalog;
  } else {
    catalog = await fetchCatalog('https://game.spacemolt.com');
  }
  const doc = generateRecipesDoc(catalog);
  writeFileSync(OUT_PATH, doc);
  console.log(`wrote ${OUT_PATH}`);
}

if (import.meta.main) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
